# Generated by Django 2.2.1 on 2019-07-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimage_thumbnail'),
    ]

    operations = [
    ]
